#!/usr/bin/env python3
"""
Convert Magic's hierarchical ext2spice output into a gate-level Verilog netlist.

Reads the .subckt headers to learn each cell's port order (Magic reorders the
pins relative to the PDK, so this must not be assumed), then emits named
connections for every instance in the top-level subckt.
"""

import re
import sys

# Physical-only cells: no logical function, drop them from the netlist.
# clkbuf / dlyclkbuf are real buffers and are deliberately NOT here.
# Physical-only cells with no logical function.
# NOTE: conb_1 is NOT here -- it is a tie-high/tie-low cell that drives real
# constant nets. Dropping it leaves those nets undriven.
SKIP = ("__decap", "__fill", "__tapvpwrvgnd", "__tap_", "__diode",
        "__decaphe", "__fakediode")

VALID_ID = re.compile(r"^[A-Za-z_][A-Za-z0-9_$]*$")
VERILOG_KEYWORDS = {"input", "output", "wire", "reg", "module", "endmodule",
                    "and", "or", "not", "nand", "nor", "xor", "xnor", "buf",
                    "supply0", "supply1", "assign", "parameter", "begin", "end"}


def vid(name):
    """Make a Verilog identifier. Magic net names contain '#' and '/'."""
    if VALID_ID.match(name) and name not in VERILOG_KEYWORDS:
        return name
    return "\\" + name + " "


def logical(cell):
    return not any(s in cell for s in SKIP)


def read_lines(path):
    """Yield logical lines, joining SPICE '+' continuations, dropping comments."""
    out = []
    for raw in open(path, errors="replace"):
        line = raw.rstrip("\n")
        if not line.strip() or line.lstrip().startswith("*"):
            continue
        if line.lstrip().startswith("+"):
            if out:
                out[-1] += " " + line.lstrip()[1:].strip()
            continue
        out.append(line.strip())
    return out


def parse(path):
    ports, insts, cur = {}, {}, None
    for line in read_lines(path):
        tok = line.split()
        low = tok[0].lower()
        if low == ".subckt":
            cur = tok[1]
            ports[cur] = tok[2:]
            insts[cur] = []
        elif low == ".ends":
            cur = None
        elif cur and tok[0][0].upper() == "X":
            # strip w=/l=/ad=... parameter tokens
            body = [t for t in tok[1:] if "=" not in t]
            if not body:
                continue
            insts[cur].append((tok[0], body[-1], body[:-1]))
    return ports, insts


def main():
    args = [a for a in sys.argv[1:]]
    top = None
    if "--top" in args:
        i = args.index("--top")
        top = args[i + 1]
        del args[i:i + 2]
    if not args:
        sys.exit("usage: spice2v.py <netlist.spice> [--top NAME]")

    ports, insts = parse(args[0])
    if not ports:
        sys.exit("no .subckt found -- did you extract with hierarchy on?")

    if top is None:
        used = {cell for lst in insts.values() for _, cell, _ in lst}
        cands = [c for c in ports if c not in used]
        if len(cands) != 1:
            sys.exit("ambiguous top, pass --top. candidates: " + ", ".join(cands))
        top = cands[0]

    kept = [(n, c, nets) for n, c, nets in insts[top]
            if c in ports and logical(c)]
    dropped = len(insts[top]) - len(kept)

    # Collect internal nets
    portset = set(ports[top])
    nets = set()
    for _, cell, conn in kept:
        nets.update(conn)
    internal = sorted(nets - portset)

    print("// generated by spice2v.py from %s" % args[0])
    print("// %d instances kept, %d physical-only cells dropped"
          % (len(kept), dropped))
    print("`default_nettype none")
    print()
    print("module %s (%s);" % (top, ", ".join(vid(p) for p in ports[top])))
    print()
    for p in ports[top]:
        print("  inout  %s;   // set direction by hand" % vid(p))
    print()
    for n in internal:
        print("  wire %s;" % vid(n))
    print()
    for name, cell, conn in kept:
        pins = ports[cell]
        if len(pins) != len(conn):
            print("  // WARNING arity mismatch on %s (%s): %d pins, %d nets"
                  % (name, cell, len(pins), len(conn)))
        pairs = ", ".join(".%s(%s)" % (p, vid(n))
                          for p, n in zip(pins, conn))
        print("  %s %s (%s);" % (cell, vid(name), pairs))
    # report nets that are read but never driven
    OUTPINS = {"X", "Y", "Q", "Q_N", "HI", "LO", "COUT", "SUM", "CO",
               "COUT_N", "SUM_N", "GCLK"}
    driven = set(portset)
    for _n, cell, conn in kept:
        for p, net in zip(ports[cell], conn):
            if p in OUTPINS:
                driven.add(net)
    undriven = sorted(n for n in nets if n not in driven and n not in ("VPWR", "VGND"))
    if undriven:
        print()
        print("  // WARNING: %d net(s) read but never driven:" % len(undriven))
        for n in undriven:
            print("  //   %s" % n)

    print()
    print("endmodule")
    print("`default_nettype wire")

    sys.stderr.write("top=%s  instances=%d  dropped=%d  internal nets=%d\n"
                     % (top, len(kept), dropped, len(internal)))


if __name__ == "__main__":
    main()
